sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Tw/b/Bl+7ApEh9WX3wpR8tpX/LOZjdx+VUqowHVgZLhMd+7iGLnI0F1FfAK3prDtoInjNaiFm9ou46SgfEcgKy1C2GdR1ODzcjQM9JDYkrzHRriIKrOpoPVTx7HygEJ0g3gdIi5zFFS3AZEs/iSc/gPrApMI87sVvH6Dj8edvKS4tlBnXOs7Mdf8N25DiC6I626F8pTtnFqN7n4oQ7ID09mbfg13s8BYhccgzyIf9gmLAPsAs+e9BhZhs+8TTTKNikIkuE1Q6l7tMyEaGoRMGgntJZrLOeewJo0+JwF34HtqatwCi166SwBCKKnnmQKMeeKL1tNSki6ETVbHzl/2BEEa0cfeWK4025tlq8ORVoDiWY94LUUIJHaisErWnXOpCDKcRTRMVIujYtnNDoVDaypHi/z5vNFF6e4zneGwN5iOAd07IINtpQZQm/tDm2OUbK02L6AR/7bXojntZRWjm5yDXvnFkeC6Yen1FswcClHjT9gdmavySLiJQwxbr09JT8S09//GsWkKb+pN7Bwb91kf1TcD5vIgSPsyu5bb9+9+f6qKlCaRN5vfa367HDtz9ObkbgFCukNJsH+gEG3ihIvMcu0SgrqbW0LjgX2JHUigGKNqDb3LAz1pOu2GSZ22aTBh2Dd5RBvdq52akm9Tmd7l8DgoFvRvmmrAmvgOaCQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Nuts-A-Christmas-Story-for-my-Children-and-Grandchildren_5591
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy